#!/bin/bash

red="\033[38;5;9m"
green="\033[1;38;5;2m"
blue="\033[38;5;4m"
magenta="\033[38;5;5m"
purple="\033[38;5;5m"
yellow="\033[38;5;3m"
creset="\033[0m"

echo -e "${magenta}    ✧ Hello Again! ✧         ✧            ✧    "
echo -e "${magenta}✧   ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄   ✧  ${red}__ ${green}__ ${blue}__ __"
echo -e "${magenta}   ✧█▒▒░░░░░░░░░▒▒█      ${red}\\ V${green}\\ V${blue}\\ V /"
echo -e "${magenta} ▄▄  █░░█░░░░░█░░█ ✧     ${red} \\_/${green}\\_/${blue}\\_/"
echo -e "${magenta}█░░█  █░░░▀█▀░░░█     ✧              ✧          "
echo -e "${magenta}█░░█  ▀▄░░░░░░░▄▀ ✧      Have a nice day :)${CRESET}"
echo -e "${CRESET}"