name: I'm using VirtualBox 6.1.26/6.1.28 OR I upgraded to MacOS 12/Monterey
description: Using VirtualBox and getting site timeouts? hostonly network adapter errors? Recently upgraded to MacOS 12?
labels: [ 'type:support' ]
body:
  - type: markdown
    attributes:
      value: |
        "
        ## MacOS 12 Monterey

        ***Do not upgrade to Monterey.***

        There are no known working versions of VirtualBox for MacOS 12, do not upgrade. ***VirtualBox intend to fix this in v6.1.29***.
        
        Until VirtualBox 6.1.29 is officially released, do not upgrade past MacOS 11 Big Sur. Test release builds are not guaranteed to work.
        
        The fastest way to restore VirtualBox is to downgrade back to MacOS 11 Big Sur, and use v6.1.24.

        ### But My New M1 Mac Only Support MacOS 12!
        Use Parallels, new Macs don't support VirtualBox.

        ## Timeouts and VirtualBox 6.1.26 and 6.1.28
        These versions of VirtualBox are known to have networking problems on Linux/Windows/MacOS, not everybody encounters these problems though.
        VirtualBox v6.1.24 works though, stick to v6.1.24 until we can confirm if 6.1.29 fixes the problems.
        
        ---
        "
  - type: textarea
    id: what-happened
    attributes:
      label: I have news related to this!
      description: Did they relelase 6.1.29? Is there a change to the vagrant file that can be made?
      placeholder: Tell us what you know!
    validations:
      required: true
