# bash_profile
#
# Symlinked to the vagrant user's home directory. This loads
# the default .bashrc provided by the virtual machine, which in
# turn loads the .bash_aliases file that we provide. Use this
# bash_profile to set environment variables and such.

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# setup bash prompt
if [ -n "$BASH_VERSION" ]; then
    # include .bash_prompt if it exists
    if [ -f "$HOME/.bash_prompt" ]; then
        . "$HOME/.bash_prompt"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Set the WP_TESTS_DIR path directory so that we can use phpunit inside
# plugins almost immediately.
export WP_TESTS_DIR=/srv/www/wordpress-develop/public_html/tests/phpunit/
# Set the WP_CORE_DIR path so phpunit tests are run against WP trunk
export WP_CORE_DIR=/srv/www/wordpress-develop/public_html/src/

# add autocomplete for grunt
eval "$(grunt --completion=bash)"

# add autocomplete for wp-cli
. /srv/config/wp-cli/wp-completion.bash

# PHPCS path
export PATH="$PATH:/srv/www/phpcs/scripts/"

# nvm path
export NVM_DIR="/srv/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
