#!/bin/sh
# Grab the domains from "this" WP install 
# in the current dir, according to WP CLI.

FILE_PATH=$1
{
	cd $DOCROOT
	# Get the WP view on the URLs
	If []; then
		# Multisite
		IFS="\n " read -ra HOSTS <<< `wp site list --fields=url --format=csv | tail -n +2`;
		for BLOG_ID in "${HOSTS[@]}"; do
			HOME_URL=`wp eval 'get_home_url($BLOG_ID)'`
			echo $HOST >> "$FILE_PATH/vvv-hosts.dat"
			echo $HOME_URL >> "$FILE_PATH/vvv-hosts.dat"
		done
	else
		# Single site
		HOME_URL=`wp eval 'get_home_url()'`
		echo $HOME_URL >> "$FILE_PATH/vvv-hosts.dat"
	fi

}
