#!/bin/bash
#
# A script to convert the included develop.svn.wordpress.org repository into
# the git mirror, develop.git.wordpress.org.

set -e

if [[ $USER != 'vagrant' ]]; then
	echo "Please run inside Vagrant"
	exit 1
fi

cd /srv/www/wordpress-develop/

if [[ -e .git ]]; then
	echo "Repo has already been converted to Git"
	exit 1
fi

echo "Converting src.wordpress-develop.dev from SVN to GIT"

echo "Rename .svn to .svn-backup"
mv .svn .svn-backup

git clone --no-checkout git://develop.git.wordpress.org/ /tmp/wp-git
cd /tmp/wp-git
git reset -q .
cd /srv/www/wordpress-develop/

echo "Moving .git dir to /srv/www/wordpress-develop/"
mv /tmp/wp-git/.git .git
git config core.fileMode false
git config diff.noprefix true

echo "Done"
