#!/bin/bash
set -eo pipefail


source /srv/provision/provision-helpers.sh

# Grab the currently active PHP mods, and lowercase it for comparison
enabled_mods=$(php -m)
enabled_mods=${enabled_mods,,}

# These PHPMods all interfere with each other in some way
phpmods=(
	"xdebug"
	"xhgui"
	"tideways_xhprof"
	"pcov"
)

# The mod that the user wants enabled, `none` for vanilla PHP
mod=${1:-none}
mod=${mod,,}

disable_phpmods() {
	# declare that our first param is an array
	declare -a mods=("${!1}")

	# Take the mods array and turn it into a commar separated list
	local mods_joined=$(printf ", %s" "${mods[@]}")
	mods_joined=${mods_joined:1}
	mods_joined="${mods_joined#"${mods_joined%%[![:space:]]*}"}"
	#vvv_info " * Disabling if present: <b>'${mods_joined}'</b>"

	for i in "${mods[@]}"
	do
		if [[ ${enabled_mods,,} == *"${i}"* ]]; then
			vvv_info " * Disabling active PHP debug mod: <b>'${i}'</b>"
			sudo phpdismod "${i}"
		fi
	done
}

enable_phpmod() {
	vvv_info " * Enabling PHP debug mod: <b>'${1}'</b>"
	sudo phpenmod "${1}"
}

restart_phpfpm() {
	vvv_info " * Restarting PHP FPM services so that the change takes effect"
	find /etc/init.d/ -name "php*-fpm" -exec bash -c 'sudo service "$(basename "$0")" restart' {} \;
}

#vvv_info " * Disabling active debug PHP mods"
disable_phpmods phpmods[@]

if [[ "${mod}" == "none" ]]; then
	restart_phpfpm
  vvv_success " * All PHP Debug mods are now turned off."
	exit 0
fi


# Tideways needs 2 mods enabling
if [[ "${mod}" == "tideways" ]]; then
	enable_phpmod "xhgui"
	enable_phpmod "tideways_xhprof"
	restart_phpfpm
  vvv_success " * PHP Debug mod switch to <b>${mod}</b><success> complete.</success>"
	exit 0
fi

if [[ "${mod}" == "xdebug" ]]; then
	# Ensure the log file for xdebug is group writeable.
	vvv_info " * Making sure log/php/xdebug-remote.log is readable and present"
	sudo touch /var/log/php/xdebug-remote.log
	sudo chmod 664 /var/log/php/xdebug-remote.log
fi

enable_phpmod "${mod}"
restart_phpfpm
vvv_success " * PHP Debug mod switch to <b>${mod}</b><success> complete.</success>"
