#!/bin/bash

echo "Disabling tideways_xhprof/xhgui"
sudo phpdismod tideways_xhprof
sudo phpdismod xhgui

echo "Restarting PHP FPM's"
find /etc/init.d/ -name "php*-fpm" -exec bash -c 'sudo service "$(basename "$0")" restart' {} \;

echo "Tideways is turned off"
