#!/bin/bash
#
# This script is run whenever `vagrant halt` is used to power off
# the virtual machine.

# Call a custom trigger command. Include an executable with this name
# in the local config/homebin directory to issue custom commands
# during `vagrant halt`.
vagrant_halt_custom