#!/bin/bash
#
# This script is run whenever `vagrant destroy` is used to destroy
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_destroy_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /srv/config/homebin/vagrant_destroy_custom ]]; then
	echo "Executing vagrant_destroy_custom"
	/srv/config/homebin/vagrant_destroy_custom
else
	/srv/config/homebin/db_backup
fi