#!/bin/bash
#
# This script is run whenever `vagrant halt` is used to power off
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_halt_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /srv/config/homebin/vagrant_halt_custom ]]; then
	echo "Executing vagrant_halt_custom"
	/srv/config/homebin/vagrant_halt_custom
else
	/srv/config/homebin/db_backup
fi