#!/bin/bash
#
# This script is run after a provision. To customize this behavior,
# include a file in your local VVV/config/homebin
# directory: vagrant_provision_custom
#
# Note that sometimes provisioning happens on `vagrant up --provision`
# so if you have a vagrant_up_custom file, be careful of double
# execution
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.

echo "Post Vagrant provision script"

if [[ -f /vagrant/config/homebin/vagrant_provision_custom ]]; then
	echo "Custom vagrant provision script found, executing vagrant_provision_custom"
	/vagrant/config/homebin/vagrant_provision_custom
fi

echo "Restarting Nginx and MySQL"
sudo service nginx restart
sudo service mysql restart

green="\033[01;32m"
echo ""
echo -e "${green}         yay  "
echo -e "${green}   ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄                __ __ __ __"
echo -e "${green}   █▒▒░░░░░░░░░▒▒█    Thanks for  \ V\ V\ V /"
echo -e "${green}    █░░█░░░░░█░░█     using        \_/\_/\_/"
echo -e "${green} ▄▄  █░░░▀█▀░░░█  ▄▄ "
echo -e "${green}█░░█ ▀▄░░░░░░░▄▀ █░░█ Provisioning has finished! Visit http://vvv.test"
echo -e "\033[0m"