#!/bin/bash
#
# This script is run whenever `vagrant suspend` is used to suspend
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_suspend_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /srv/config/homebin/vagrant_suspend_custom ]]; then
	echo "Executing vagrant_suspend_custom"
	/srv/config/homebin/vagrant_suspend_custom
else
    # Load vvv-config.yml
    VVV_CONFIG=/vagrant/vvv-config.yml
    if [[ -f /vagrant/vvv-custom.yml ]]; then
        VVV_CONFIG=/vagrant/vvv-custom.yml
    fi

    # Check if backups are turned on or off
    run_backups=`cat ${VVV_CONFIG} | shyaml get-value general.db_backup 2> /dev/null`

    if [[ $run_backups != "False" ]]
    then
	    /srv/config/homebin/db_backup
    fi
fi
