#!/bin/bash
#
# This script is run whenever `vagrant destroy` is used to destroy
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_destroy_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /srv/config/homebin/vagrant_destroy_custom ]]; then
	echo "Executing vagrant_destroy_custom"
	/srv/config/homebin/vagrant_destroy_custom
else
    # Load config.yml
    VVV_CONFIG=/srv/config/default-config.yml
    if [[ -f /srv/config/config.yml ]]; then
        VVV_CONFIG=/srv/config/config.yml
    fi

    # Check if backups are turned on or off
    run_backups=`cat ${VVV_CONFIG} | shyaml -q get-value general.db_backup.enable`
    if [[ -z "$run_backups" ]]; then
      run_backups=`cat ${VVV_CONFIG} | shyaml -q get-value general.db_backup`
    fi

    if [[ $run_backups != "False" ]]; then
      /srv/config/homebin/db_backup
    fi

    echo ""
    echo -e "         !!!  "
    echo -e "   ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄                  __ __ __ __"
    echo -e "   █▒▒░░░░░░░░░▒▒█    Farewell      \ V\ V\ V /"
    echo -e "    █░░X░░░░░X░░█     virtual world  \_/\_/\_/"
    echo -e "     █░░░▀█▀░░░█   "
    echo -e " ▄▄  ▀▄░░░░░░░▄▀ ▄▄   Don't forget to make a new teddy bear"
    echo -e "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  with vagrant up --provision"
    echo -e "\033[0m"
fi
