#!/bin/bash
#
# This script is run whenever `vagrant suspend` is used to suspend
# the virtual machine. To customize this behavior, include a file
# in your local VVV/config/homebin directory: vagrant_suspend_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /home/vagrant/bin/vagrant_suspend_custom ]]; then
	vagrant_suspend_custom
else
	db_backup
fi