#!/usr/bin/env bash

# Load config.yml
VVV_CONFIG=/srv/config/default-config.yml
if [[ -f /srv/config/config.yml ]]; then
    VVV_CONFIG=/srv/config/config.yml
fi

DEFAULTPHP=$(cat ${VVV_CONFIG} | shyaml -q get-value general.php_cli_version "8.2")
php_version=$(readlink -f /usr/bin/php)
if [[ $php_version != *"${DEFAULTPHP}"* ]]; then
  echo " * Restoring the default PHP CLI version ( ${DEFAULTPHP} )"
  update-alternatives --set php "/usr/bin/php${DEFAULTPHP}"
  update-alternatives --set phar "/usr/bin/phar${DEFAULTPHP}"
  update-alternatives --set phar.phar "/usr/bin/phar.phar${DEFAULTPHP}"
  update-alternatives --set phpize "/usr/bin/phpize${DEFAULTPHP}"
  update-alternatives --set php-config "/usr/bin/php-config${DEFAULTPHP}"
  echo " * Restoration complete"
fi
