#!/bin/bash
sudo phpdismod tideways_xhprof
sudo phpdismod xhgui
sudo phpenmod xdebug

find /etc/init.d/ -name "php*-fpm" -exec bash -c 'echo "Restarting $(basename "$0" ) " && sudo service "$(basename "$0")" restart' {} \;

# Ensure the log file for xdebug is group writeable.
sudo touch /var/log/php/xdebug-remote.log
sudo chmod 664 /var/log/php/xdebug-remote.log
