#!/bin/bash
echo "Disabling XDebug if it's present"
sudo phpdismod xdebug

echo "Restarting PHP FPM's"
find /etc/init.d/ -name "php*-fpm" -exec bash -c 'sudo service "$(basename "$0")" restart' {} \;

echo "XDebug is turned off"
