name: Auto Labelling Checks
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  build:
    name: AutoLabelling
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels on Issues
        if: github.event_name == 'issues'
        uses: offensive-vk/auto-label@v8
        with:
          create-labels: true # Optional, defaults to true
          auth-token: ${{ github.token }} # Optional, defaults to ${{ secrets.GITHUB_TOKEN }}
          issue-config: .github/issue-labels.yml # Required, path to the issue configuration file.
