name: Syntax Checking and Linting
on:
  [pull_request]
    
jobs:
  build:
    name: Linting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v0.0.1
        with:
          file_or_dir: .
      - name: PHP Syntax Checker (Lint) PHP 7.3
        uses: StephaneBour/actions-php-lint@7.3
        with:
          dir: '.'
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Ruby version specified in `.ruby-version`
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop
        run: gem install rubocop && rubocop -c .rubocop.yml .vvv/
