name: Syntax Checking and Linting
on:
  [pull_request]
    
jobs:
  build:
    name: Linting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
      - name: PHP Syntax Checker (Lint) PHP 8.2
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: '.'
      - name: Shell Script Syntax Checks
        uses: Klintrup/simple-shell-syntax-check@v2
